### PR TITLE
First Pass Model Notebook

### PR DESCRIPTION
**Pull request by ChrisHartig44**
initial model

# Description
Random Forest classiifer model to distinguish between instances of police use of force and other reddit posts

# Number of Files changed
1
# Questions for Reviewer

# Type of Change
- [x] New Feature
- [ ] Feature Update
- [ ] Fix Error

# Status
- [x] Tested

### CODE REVIEW

**Review by zacharyluck — APPROVED** [review]
Very helpful, will implement this code into the API to filter results.

**Comment by zacharyluck** [comment]
# Description
Move notebook to correct folder

# Number of Files changed
1
# Questions for Reviewer

# Type of Change
- [ ] New Feature
- [ ] Feature Update
- [x] Fix Error

# Status
- [x] Tested

**Review by zacharyluck — APPROVED** [review]
Updates added, looks good now.

**Review by exploratum — APPROVED** [review]
Thanks for taking care of this

**Pull request merged**
